version: '3.8'

services:
  api:
    build:
      context: .
      target: production
    restart: always
    environment:
      - NODE_ENV=production
      - THREADS_APP_ID=${THREADS_APP_ID}
      - THREADS_APP_SECRET=${THREADS_APP_SECRET}
      - THREADS_REDIRECT_URI=${THREADS_REDIRECT_URI}
      - CLIENT_TOKEN=${CLIENT_TOKEN}
    ports:
      - "3000:3000"
