version: '3.8'

services:
  api:
    image: ghcr.io/${GITHUB_REPOSITORY}/threads-bot-api:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add other environment variables as needed
    volumes:
      - ./data:/app/data
