version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - THREADS_APP_ID=${THREADS_APP_ID}
      - THREADS_APP_SECRET=${THREADS_APP_SECRET}
      - THREADS_REDIRECT_URI=${THREADS_REDIRECT_URI}
      - CLIENT_TOKEN=${CLIENT_TOKEN}
    volumes:
      - .:/app
      - /app/node_modules
