version: '3.8'

services:
  api:
    image: ghcr.io/${GITHUB_REPOSITORY}/threads-bot-api:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "80:3000"
      - "443:3000" # If you'll use HTTPS
    env_file:
      - .env.production
    volumes:
      - ./data:/app/data
