version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - THREADS_APP_ID=${THREADS_APP_ID}
      - THREADS_APP_SECRET=${THREADS_APP_SECRET}
      - THREADS_REDIRECT_URI=https://threads-bot-api.loca.lt/threads/callback
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run start:dev
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  localtunnel:
    image: node:18-alpine
    depends_on:
      - api
    command: >
      sh -c "
        echo 'Getting tunnel password...' &&
        npm install -g localtunnel &&
        TUNNEL_PASSWORD=$$(wget -q -O - https://loca.lt/mytunnelpassword) &&
        echo '\n🔑 Tunnel Password: '$$TUNNEL_PASSWORD'\n' &&
        lt --port 3000 --subdomain threads-bot-api --print-requests"
    restart: unless-stopped
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    healthcheck:
      test: [ "CMD", "wget", "--spider", "https://threads-bot-api.loca.lt" ]
      interval: 30s
      timeout: 10s
      retries: 3
