name: Main Branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Start application with Docker Compose
        run: |
          docker compose -f docker-compose.prod.yml up -d
        env:
          THREADS_APP_ID: ${{ secrets.THREADS_APP_ID }}
          THREADS_APP_SECRET: ${{ secrets.THREADS_APP_SECRET }}
          THREADS_REDIRECT_URI: ${{ secrets.THREADS_REDIRECT_URI }}
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}

      - name: Health check
        run: |
          sleep 10
          curl -sSf http://localhost:3000/health || (docker compose -f docker-compose.prod.yml logs && exit 1)