name: Main Branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Create env file
        run: |
          cat << EOF > .env
          THREADS_APP_ID=${{ vars.THREADS_APP_ID }}
          THREADS_APP_SECRET=${{ vars.THREADS_APP_SECRET }}
          THREADS_REDIRECT_URI=${{ vars.THREADS_REDIRECT_URI }}
          CLIENT_TOKEN=${{ vars.CLIENT_TOKEN }}
          EOF

      - name: Start application with Docker Compose
        run: docker compose -f docker-compose.prod.yml up -d
        env:
          THREADS_APP_ID: ${{ vars.THREADS_APP_ID }}
          THREADS_APP_SECRET: ${{ vars.THREADS_APP_SECRET }}
          THREADS_REDIRECT_URI: ${{ vars.THREADS_REDIRECT_URI }}
          CLIENT_TOKEN: ${{ vars.CLIENT_TOKEN }}

      - name: Health check
        run: |
          sleep 30
          curl -sSf http://localhost:3000/api/health || (docker compose -f docker-compose.prod.yml logs && exit 1)